import type { Question } from "../questionTypes";

export const lesson: Question = {
  "id": "fe-controlled-components",
  "track": "Frontend",
  "category": "React",
  "level": "Foundational",
  "question": "What is the difference between controlled and uncontrolled components in React?",
  "lessonSections": [
    {
      "title": "Learn it",
      "body": "When people talk about controlled and uncontrolled components, they are usually talking about form inputs. The question is simple: who is currently in charge of the input's value?\n\nIn a controlled component, React state is the source of truth. The input shows whatever value React gives it, and every user change goes through React.\n\n```jsx\nfunction SearchBox() {\n  const [query, setQuery] = useState(\"\");\n\n  return (\n    <input\n      value={query}\n      onChange={(event) => setQuery(event.target.value)}\n    />\n  );\n}\n```\n\nHere, the browser does not get to quietly keep its own final answer. The input displays `query`. When the user types, `onChange` updates `query`. React renders again, and the input displays the new value.\n\nIn an uncontrolled component, the browser keeps the current value inside the DOM input. React may set an initial value, but React does not update state on every keystroke.\n\n```jsx\nfunction SearchBox() {\n  const inputRef = useRef(null);\n\n  function handleSubmit() {\n    console.log(inputRef.current.value);\n  }\n\n  return <input ref={inputRef} defaultValue=\"\" />;\n}\n```\n\nThe mental model is: controlled means React owns the value. Uncontrolled means the DOM owns the value, and React reads it when needed."
    },
    {
      "title": "Walkthrough",
      "body": "Imagine a signup form with an email field.\n\nIf the field is controlled, the app can react immediately as the user types. It can disable the submit button until the email looks valid. It can show an error. It can transform text. It can keep multiple fields in sync. It can reset the field by setting state back to an empty string.\n\n```jsx\nfunction SignupForm() {\n  const [email, setEmail] = useState(\"\");\n  const isValid = email.includes(\"@\");\n\n  return (\n    <form>\n      <input value={email} onChange={(event) => setEmail(event.target.value)} />\n      <button disabled={!isValid}>Create account</button>\n    </form>\n  );\n}\n```\n\nIf the field is uncontrolled, React does less work during typing. This can be fine when you only need the value at submit time.\n\n```jsx\nfunction SignupForm() {\n  const emailRef = useRef(null);\n\n  function handleSubmit(event) {\n    event.preventDefault();\n    const email = emailRef.current.value;\n    console.log(email);\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <input ref={emailRef} name=\"email\" />\n      <button>Create account</button>\n    </form>\n  );\n}\n```\n\nNeither approach is automatically better. Controlled inputs give you direct product control. Uncontrolled inputs can be simpler when the browser can manage the field and you only need to read the value later."
    },
    {
      "title": "Make it practical",
      "body": "Use controlled inputs when the UI depends on the current value. Examples include live validation, dependent fields, formatting, search as you type, disabling buttons, preview panes, and forms that need to be reset from app state.\n\nUse uncontrolled inputs when you only need a value at the end, especially for small forms, file inputs, or cases where a form library handles the DOM details for you.\n\nThe most important rule is consistency. An input should not switch between controlled and uncontrolled during its lifetime. This often happens when a controlled `value` starts as `undefined` and later becomes a string.\n\n```jsx\n// Risky because name might be undefined at first.\n<input value={name} onChange={handleChange} />\n\n// Safer because the input is always controlled with a string.\n<input value={name ?? \"\"} onChange={handleChange} />\n```\n\nThat tiny detail matters because React needs to know who owns the input. If ownership changes halfway through, bugs become confusing."
    },
    {
      "title": "Common mistakes",
      "body": "A common mistake is using `value` without `onChange`. That makes the input controlled but impossible to edit, because React keeps forcing the same value back into the field.\n\nAnother mistake is using `defaultValue` and expecting it to update later when props change. `defaultValue` only sets the initial DOM value. If the value needs to follow React state, use `value`.\n\nA third mistake is assuming controlled components are only about forms. The deeper idea is ownership. The same product question appears everywhere: should this thing manage itself locally, or should the parent/app own the state because other parts of the UI depend on it?"
    }
  ],
  "answer": "When people talk about controlled and uncontrolled components, they are usually talking about form inputs. The question is simple: who is currently in charge of the input's value?",
  "reasoning": "Use controlled inputs when the UI depends on the current value. Examples include live validation, dependent fields, formatting, search as you type, disabling buttons, preview panes, and forms that need to be reset from app state.\n\nUse uncontrolled inputs when you only need a value at the end, especially for small forms, file inputs, or cases where a form library handles the DOM details for you.\n\nThe most important rule is consistency. An input should not switch between controlled and uncontrolled during its lifetime. This often happens when a controlled `value` starts as `undefined` and later becomes a string.\n\n```jsx\n// Risky because name might be undefined at first.\n<input value={name} onChange={handleChange} />\n\n// Safer because the input is always controlled with a string.\n<input value={name ?? \"\"} onChange={handleChange} />\n```\n\nThat tiny detail matters because React needs to know who owns the input. If ownership changes halfway through, bugs become confusing.",
  "tests": "Use the prompts to check whether the idea is clear enough to explain without memorizing.",
  "followUps": [
    "Who owns the value in a controlled input?",
    "Why does a controlled input need `onChange`?",
    "What is `defaultValue` for?",
    "When might an uncontrolled input be enough?",
    "Why is switching between controlled and uncontrolled input state a problem?"
  ],
  "interviewAnswer": "A controlled component gets its value from React state and reports changes back through an event handler. An uncontrolled component keeps its current value in the DOM, usually accessed with a ref or form submission.\n\nControlled inputs are best when the UI needs to respond to the value immediately, such as validation, previews, dependent fields, resets, or submit-button state. Uncontrolled inputs are useful when the browser can own the field until submit time. A good answer should mention source of truth, `value` versus `defaultValue`, `onChange`, refs, and the warning caused by switching ownership during the component's lifetime.",
  "sourceLinks": [
    {
      "label": "React: input component",
      "url": "https://react.dev/reference/react-dom/components/input"
    },
    {
      "label": "React: Sharing state between components",
      "url": "https://react.dev/learn/sharing-state-between-components"
    }
  ],
  "beginnerExplanation": "When people talk about controlled and uncontrolled components, they are usually talking about form inputs. The question is simple: who is currently in charge of the input's value?\n\nIn a controlled component, React state is the source of truth. The input shows whatever value React gives it, and every user change goes through React.\n\n```jsx\nfunction SearchBox() {\n  const [query, setQuery] = useState(\"\");\n\n  return (\n    <input\n      value={query}\n      onChange={(event) => setQuery(event.target.value)}\n    />\n  );\n}\n```\n\nHere, the browser does not get to quietly keep its own final answer. The input displays `query`. When the user types, `onChange` updates `query`. React renders again, and the input displays the new value.\n\nIn an uncontrolled component, the browser keeps the current value inside the DOM input. React may set an initial value, but React does not update state on every keystroke.\n\n```jsx\nfunction SearchBox() {\n  const inputRef = useRef(null);\n\n  function handleSubmit() {\n    console.log(inputRef.current.value);\n  }\n\n  return <input ref={inputRef} defaultValue=\"\" />;\n}\n```\n\nThe mental model is: controlled means React owns the value. Uncontrolled means the DOM owns the value, and React reads it when needed.",
  "example": "Imagine a signup form with an email field.\n\nIf the field is controlled, the app can react immediately as the user types. It can disable the submit button until the email looks valid. It can show an error. It can transform text. It can keep multiple fields in sync. It can reset the field by setting state back to an empty string.\n\n```jsx\nfunction SignupForm() {\n  const [email, setEmail] = useState(\"\");\n  const isValid = email.includes(\"@\");\n\n  return (\n    <form>\n      <input value={email} onChange={(event) => setEmail(event.target.value)} />\n      <button disabled={!isValid}>Create account</button>\n    </form>\n  );\n}\n```\n\nIf the field is uncontrolled, React does less work during typing. This can be fine when you only need the value at submit time.\n\n```jsx\nfunction SignupForm() {\n  const emailRef = useRef(null);\n\n  function handleSubmit(event) {\n    event.preventDefault();\n    const email = emailRef.current.value;\n    console.log(email);\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <input ref={emailRef} name=\"email\" />\n      <button>Create account</button>\n    </form>\n  );\n}\n```\n\nNeither approach is automatically better. Controlled inputs give you direct product control. Uncontrolled inputs can be simpler when the browser can manage the field and you only need to read the value later.",
  "commonMistakes": "A common mistake is using `value` without `onChange`. That makes the input controlled but impossible to edit, because React keeps forcing the same value back into the field.\n\nAnother mistake is using `defaultValue` and expecting it to update later when props change. `defaultValue` only sets the initial DOM value. If the value needs to follow React state, use `value`.\n\nA third mistake is assuming controlled components are only about forms. The deeper idea is ownership. The same product question appears everywhere: should this thing manage itself locally, or should the parent/app own the state because other parts of the UI depend on it?"
};
