import type { Question } from "../questionTypes";

export const lesson: Question = {
  "id": "fe-closures",
  "track": "Frontend",
  "category": "JavaScript",
  "level": "Foundational",
  "question": "Explain closures in JavaScript.",
  "lessonSections": [
    {
      "title": "Learn it",
      "body": "A closure is one of those JavaScript ideas that sounds abstract until you connect it to something very simple: where variables live, and which functions can still reach them.\n\nStart with scope. Scope means the area of code where a variable is available. If you create a variable inside a function, that variable belongs to that function's local scope. Code outside the function cannot normally reach it directly. This is useful because it keeps temporary details private.\n\nNow add nested functions. In JavaScript, an inner function can use variables from the outer function where it was written. This is called lexical scoping. Lexical means JavaScript decides variable access from the physical structure of the code, not from where the function is eventually called.\n\nHere is the first step:\n\n```js\nfunction init() {\n  const name = \"Ada\";\n\n  function displayName() {\n    console.log(name);\n  }\n\n  displayName();\n}\n\ninit();\n```\n\n`displayName` does not have its own `name` variable. JavaScript looks around the function and finds `name` in the outer `init` scope. That part is lexical scoping.\n\nA closure appears when the inner function keeps access to that outer scope even after the outer function has finished running. That is the part that surprises people."
    },
    {
      "title": "Walkthrough",
      "body": "Look at this version carefully:\n\n```js\nfunction makeGreeter() {\n  const name = \"Ada\";\n\n  function greet() {\n    return `Hello, ${name}`;\n  }\n\n  return greet;\n}\n\nconst sayHello = makeGreeter();\n\nsayHello(); // \"Hello, Ada\"\n```\n\nWhen `makeGreeter()` runs, it creates `name` and creates the `greet` function. Then it returns `greet`. After that, `makeGreeter()` is finished.\n\nIf you are new to closures, you may expect `name` to disappear at that point. But `sayHello` is now holding the returned `greet` function, and `greet` still refers to `name`. So JavaScript keeps the needed lexical environment alive. That combination, the function plus the variables it can still access, is the closure.\n\nAnother example makes the idea more obvious:\n\n```js\nfunction makeAdder(x) {\n  return function add(y) {\n    return x + y;\n  };\n}\n\nconst add5 = makeAdder(5);\nconst add10 = makeAdder(10);\n\nadd5(2); // 7\nadd10(2); // 12\n```\n\nBoth returned functions use the same code shape, but they remember different environments. `add5` remembers an environment where `x` is `5`. `add10` remembers an environment where `x` is `10`.\n\nThis is the key: a closure does not just remember a function body. It remembers the surrounding variables the function needs."
    },
    {
      "title": "Make it practical",
      "body": "Closures are common in frontend code because frontend code is event-based. You often define behavior now and run it later when the user clicks, types, focuses an input, or when a timer fires.\n\nFor example:\n\n```js\nfunction makeSizer(size) {\n  return function resizeBody() {\n    document.body.style.fontSize = `${size}px`;\n  };\n}\n\nconst size12 = makeSizer(12);\nconst size16 = makeSizer(16);\n\ndocument.getElementById(\"small\").onclick = size12;\ndocument.getElementById(\"large\").onclick = size16;\n```\n\nThe click handler runs later, but it still knows which `size` it was created with. That is closure doing useful work.\n\nClosures also explain private state:\n\n```js\nfunction createCounter() {\n  let count = 0;\n\n  return {\n    increment() {\n      count += 1;\n    },\n    value() {\n      return count;\n    },\n  };\n}\n\nconst counter = createCounter();\n\ncounter.increment();\ncounter.value(); // 1\n```\n\nNothing outside `createCounter` can directly touch `count`, but the returned methods can. They share access to the same hidden variable.\n\nOnce this clicks, closure bugs also become easier to understand. If a callback runs later and sees an old value, you are probably dealing with a stale closure. If a long-lived listener keeps a large object alive, closure lifetime may be part of the memory problem."
    },
    {
      "title": "Common mistakes",
      "body": "A common beginner mistake is thinking a closure copies a value once and freezes it forever. That is not quite right. A closure keeps access to a variable environment. If multiple functions share that environment, they can see changes made through that same environment.\n\nAnother common mistake happens with old `var` loop code. `var` is function-scoped, so callbacks created inside the loop can accidentally share the same changing variable. Modern `let` and `const` create block-scoped bindings, which usually avoids that problem.\n\nDo not treat closures as rare advanced syntax. If a function uses a variable from outside itself, you are already using closure behavior."
    }
  ],
  "answer": "A closure is one of those JavaScript ideas that sounds abstract until you connect it to something very simple: where variables live, and which functions can still reach them.",
  "reasoning": "Closures are common in frontend code because frontend code is event-based. You often define behavior now and run it later when the user clicks, types, focuses an input, or when a timer fires.\n\nFor example:\n\n```js\nfunction makeSizer(size) {\n  return function resizeBody() {\n    document.body.style.fontSize = `${size}px`;\n  };\n}\n\nconst size12 = makeSizer(12);\nconst size16 = makeSizer(16);\n\ndocument.getElementById(\"small\").onclick = size12;\ndocument.getElementById(\"large\").onclick = size16;\n```\n\nThe click handler runs later, but it still knows which `size` it was created with. That is closure doing useful work.\n\nClosures also explain private state:\n\n```js\nfunction createCounter() {\n  let count = 0;\n\n  return {\n    increment() {\n      count += 1;\n    },\n    value() {\n      return count;\n    },\n  };\n}\n\nconst counter = createCounter();\n\ncounter.increment();\ncounter.value(); // 1\n```\n\nNothing outside `createCounter` can directly touch `count`, but the returned methods can. They share access to the same hidden variable.\n\nOnce this clicks, closure bugs also become easier to understand. If a callback runs later and sees an old value, you are probably dealing with a stale closure. If a long-lived listener keeps a large object alive, closure lifetime may be part of the memory problem.",
  "tests": "Use the prompts to check whether the idea is clear enough to explain without memorizing.",
  "followUps": [
    "What is the difference between lexical scoping and closure?",
    "Why does `sayHello()` still know the value of `name` after `makeGreeter()` finishes?",
    "Why do `add5` and `add10` remember different values of `x`?",
    "How can closures help create private state?",
    "What kind of bug might happen when a callback remembers an old value?"
  ],
  "interviewAnswer": "A closure is a function together with references to the lexical environment where it was created. In plain terms, a function can keep access to variables from an outer scope even after that outer function has finished running.\n\nClosures matter in frontend code because callbacks, event handlers, timers, debounced functions, and hooks often run later while still depending on variables from the place where they were created. A strong answer should mention lexical scope, lifetime, practical uses like private state or event callbacks, and common risks like stale values or retained memory.",
  "sourceLinks": [
    {
      "label": "MDN: Closures",
      "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Closures"
    },
    {
      "label": "Front End Interview Handbook: JavaScript questions",
      "url": "https://www.frontendinterviewhandbook.com/javascript-questions/"
    }
  ],
  "beginnerExplanation": "A closure is one of those JavaScript ideas that sounds abstract until you connect it to something very simple: where variables live, and which functions can still reach them.\n\nStart with scope. Scope means the area of code where a variable is available. If you create a variable inside a function, that variable belongs to that function's local scope. Code outside the function cannot normally reach it directly. This is useful because it keeps temporary details private.\n\nNow add nested functions. In JavaScript, an inner function can use variables from the outer function where it was written. This is called lexical scoping. Lexical means JavaScript decides variable access from the physical structure of the code, not from where the function is eventually called.\n\nHere is the first step:\n\n```js\nfunction init() {\n  const name = \"Ada\";\n\n  function displayName() {\n    console.log(name);\n  }\n\n  displayName();\n}\n\ninit();\n```\n\n`displayName` does not have its own `name` variable. JavaScript looks around the function and finds `name` in the outer `init` scope. That part is lexical scoping.\n\nA closure appears when the inner function keeps access to that outer scope even after the outer function has finished running. That is the part that surprises people.",
  "example": "Look at this version carefully:\n\n```js\nfunction makeGreeter() {\n  const name = \"Ada\";\n\n  function greet() {\n    return `Hello, ${name}`;\n  }\n\n  return greet;\n}\n\nconst sayHello = makeGreeter();\n\nsayHello(); // \"Hello, Ada\"\n```\n\nWhen `makeGreeter()` runs, it creates `name` and creates the `greet` function. Then it returns `greet`. After that, `makeGreeter()` is finished.\n\nIf you are new to closures, you may expect `name` to disappear at that point. But `sayHello` is now holding the returned `greet` function, and `greet` still refers to `name`. So JavaScript keeps the needed lexical environment alive. That combination, the function plus the variables it can still access, is the closure.\n\nAnother example makes the idea more obvious:\n\n```js\nfunction makeAdder(x) {\n  return function add(y) {\n    return x + y;\n  };\n}\n\nconst add5 = makeAdder(5);\nconst add10 = makeAdder(10);\n\nadd5(2); // 7\nadd10(2); // 12\n```\n\nBoth returned functions use the same code shape, but they remember different environments. `add5` remembers an environment where `x` is `5`. `add10` remembers an environment where `x` is `10`.\n\nThis is the key: a closure does not just remember a function body. It remembers the surrounding variables the function needs.",
  "commonMistakes": "A common beginner mistake is thinking a closure copies a value once and freezes it forever. That is not quite right. A closure keeps access to a variable environment. If multiple functions share that environment, they can see changes made through that same environment.\n\nAnother common mistake happens with old `var` loop code. `var` is function-scoped, so callbacks created inside the loop can accidentally share the same changing variable. Modern `let` and `const` create block-scoped bindings, which usually avoids that problem.\n\nDo not treat closures as rare advanced syntax. If a function uses a variable from outside itself, you are already using closure behavior."
};
