import type { Question } from "../questionTypes";

export const lesson: Question = {
  "id": "tpm-success-metrics",
  "track": "TPM",
  "category": "Metrics",
  "level": "Foundational",
  "question": "How would you choose success metrics for a product feature?",
  "lessonSections": [
    {
      "title": "Learn it",
      "body": "Success metrics tell the team whether a feature is actually working. Without metrics, teams often celebrate shipping rather than impact.\n\nThe beginner mistake is choosing metrics that are easy to count but do not prove value. Page views, clicks, and signups can be useful, but they may not show whether users got the benefit the product promised.\n\nA better approach starts with the product goal.\n\nWhat user behavior should improve?\n\nWhat business outcome should improve?\n\nWhat risks should not get worse?\n\nFor example, if a feature helps users send repeat transfers faster, success might include repeat-transfer completion rate, time to complete, successful scheduled transfers, and lower support contacts. It should not only be \"number of people who clicked the new button.\""
    },
    {
      "title": "Walkthrough",
      "body": "Imagine launching a saved recipients feature in a money transfer app.\n\nThe user problem is that people repeatedly enter the same recipient details. The business goal is to increase repeat transfer completion and reduce friction.\n\nGood success metrics might include:\n\n- Percentage of repeat transfers using saved recipients.\n- Repeat transfer completion rate.\n- Average time to start and complete a repeat transfer.\n- Error rate from incorrect recipient details.\n- Support tickets about recipient entry.\n\nYou also need guardrail metrics. A guardrail metric catches harm while the main metric improves. For saved recipients, guardrails might include failed transfers, fraud alerts, mistaken recipient reports, or account takeover signals.\n\nThe feature is not successful if completion goes up because the app made it too easy to send money to the wrong person."
    },
    {
      "title": "Make it practical",
      "body": "I would choose metrics in layers.\n\nFirst, define the goal in plain language. \"Help users complete repeat transfers with less effort.\"\n\nSecond, choose an activation metric. Are users discovering and setting up the feature?\n\nThird, choose a usage metric. Are users actually using it in the intended flow?\n\nFourth, choose an outcome metric. Is the user or business result improving?\n\nFifth, choose quality and guardrail metrics. Did errors, complaints, risk, latency, or cost get worse?\n\nSixth, decide how to measure. What events do we need? What properties? What baseline period? What cohort? What time window? What dashboard? What review date?\n\nFor interview answers, it helps to avoid giving one lonely metric. A real product needs a small set: one primary success metric, supporting diagnostics, and guardrails.\n\nA strong metrics answer often looks like a small tree:\n\n```txt\nFeature:\nSaved recipients for repeat transfers\n\nProduct promise:\nRepeat senders can send to trusted recipients faster, with fewer mistakes.\n\nPrimary success metric:\nRepeat transfer completion rate for users with saved recipients.\n\nActivation metrics:\n- Percentage of eligible users who save at least one recipient\n- Percentage of repeat senders who see the saved-recipient entry point\n\nUsage metrics:\n- Percentage of repeat transfers started from saved recipients\n- Number of saved recipients used more than once\n\nEfficiency metrics:\n- Median time from \"start transfer\" to \"submit transfer\"\n- Number of recipient-detail edits per repeat transfer\n\nQuality metrics:\n- Failed transfers caused by incorrect recipient details\n- Recipient deletion or correction rate\n\nGuardrail metrics:\n- Mistaken-recipient support tickets\n- Fraud or account-takeover flags involving saved recipients\n- Transfer cancellation rate after recipient selection\n```\n\nThen define the instrumentation before launch:\n\n```txt\nEvents needed:\n- recipient_save_started\n- recipient_save_completed\n- recipient_selected\n- transfer_submitted\n- transfer_completed\n- transfer_failed\n- recipient_edited\n- recipient_deleted\n\nUseful properties:\n- user_id\n- recipient_id\n- corridor\n- payout_method\n- is_repeat_sender\n- transfer_status\n- failure_reason\n- source: saved_recipient, manual_entry, recent_recipient\n\nBaseline:\nCompare repeat-transfer completion and time-to-submit from the 30 days before launch.\n\nReview window:\nLook at early guardrails after 24 hours, then success metrics after one or two full repeat-transfer cycles.\n```\n\nThis is the difference between \"I would track conversion\" and \"I know how to prove whether the feature helped without creating new harm.\""
    },
    {
      "title": "Common mistakes",
      "body": "A common mistake is calling an output a success metric. \"Feature launched\" is a delivery milestone, not proof of user value.\n\nAnother mistake is using vanity metrics. A click can be curiosity, confusion, or success. You need context.\n\nA third mistake is choosing too many metrics. If everything is important, the team may not know what to optimize."
    }
  ],
  "answer": "Success metrics tell the team whether a feature is actually working. Without metrics, teams often celebrate shipping rather than impact.",
  "reasoning": "I would choose metrics in layers.\n\nFirst, define the goal in plain language. \"Help users complete repeat transfers with less effort.\"\n\nSecond, choose an activation metric. Are users discovering and setting up the feature?\n\nThird, choose a usage metric. Are users actually using it in the intended flow?\n\nFourth, choose an outcome metric. Is the user or business result improving?\n\nFifth, choose quality and guardrail metrics. Did errors, complaints, risk, latency, or cost get worse?\n\nSixth, decide how to measure. What events do we need? What properties? What baseline period? What cohort? What time window? What dashboard? What review date?\n\nFor interview answers, it helps to avoid giving one lonely metric. A real product needs a small set: one primary success metric, supporting diagnostics, and guardrails.\n\nA strong metrics answer often looks like a small tree:\n\n```txt\nFeature:\nSaved recipients for repeat transfers\n\nProduct promise:\nRepeat senders can send to trusted recipients faster, with fewer mistakes.\n\nPrimary success metric:\nRepeat transfer completion rate for users with saved recipients.\n\nActivation metrics:\n- Percentage of eligible users who save at least one recipient\n- Percentage of repeat senders who see the saved-recipient entry point\n\nUsage metrics:\n- Percentage of repeat transfers started from saved recipients\n- Number of saved recipients used more than once\n\nEfficiency metrics:\n- Median time from \"start transfer\" to \"submit transfer\"\n- Number of recipient-detail edits per repeat transfer\n\nQuality metrics:\n- Failed transfers caused by incorrect recipient details\n- Recipient deletion or correction rate\n\nGuardrail metrics:\n- Mistaken-recipient support tickets\n- Fraud or account-takeover flags involving saved recipients\n- Transfer cancellation rate after recipient selection\n```\n\nThen define the instrumentation before launch:\n\n```txt\nEvents needed:\n- recipient_save_started\n- recipient_save_completed\n- recipient_selected\n- transfer_submitted\n- transfer_completed\n- transfer_failed\n- recipient_edited\n- recipient_deleted\n\nUseful properties:\n- user_id\n- recipient_id\n- corridor\n- payout_method\n- is_repeat_sender\n- transfer_status\n- failure_reason\n- source: saved_recipient, manual_entry, recent_recipient\n\nBaseline:\nCompare repeat-transfer completion and time-to-submit from the 30 days before launch.\n\nReview window:\nLook at early guardrails after 24 hours, then success metrics after one or two full repeat-transfer cycles.\n```\n\nThis is the difference between \"I would track conversion\" and \"I know how to prove whether the feature helped without creating new harm.\"",
  "tests": "Use the prompts to check whether the idea is clear enough to explain without memorizing.",
  "followUps": [
    "Why is shipping not the same as success?",
    "What is a guardrail metric?",
    "Why might clicks be misleading?",
    "What is the difference between activation, usage, and outcome?",
    "What instrumentation questions should be answered before launch?"
  ],
  "interviewAnswer": "I would start with the product goal, then define a primary success metric that reflects user or business value. I would add supporting metrics to understand the funnel and guardrail metrics to catch harm.\n\nFor example, for saved recipients, I might track setup rate, repeat-transfer usage, completion rate, time to complete, failed transfers, and support tickets. A strong answer explains why each metric maps to the feature's intent.",
  "sourceLinks": [
    {
      "label": "Amplitude: North Star metric",
      "url": "https://amplitude.com/blog/north-star-metric"
    },
    {
      "label": "Atlassian Team Playbook: Goals, signals, measures",
      "url": "https://www.atlassian.com/team-playbook/plays/goals-signals-measures"
    }
  ],
  "beginnerExplanation": "Success metrics tell the team whether a feature is actually working. Without metrics, teams often celebrate shipping rather than impact.\n\nThe beginner mistake is choosing metrics that are easy to count but do not prove value. Page views, clicks, and signups can be useful, but they may not show whether users got the benefit the product promised.\n\nA better approach starts with the product goal.\n\nWhat user behavior should improve?\n\nWhat business outcome should improve?\n\nWhat risks should not get worse?\n\nFor example, if a feature helps users send repeat transfers faster, success might include repeat-transfer completion rate, time to complete, successful scheduled transfers, and lower support contacts. It should not only be \"number of people who clicked the new button.\"",
  "example": "Imagine launching a saved recipients feature in a money transfer app.\n\nThe user problem is that people repeatedly enter the same recipient details. The business goal is to increase repeat transfer completion and reduce friction.\n\nGood success metrics might include:\n\n- Percentage of repeat transfers using saved recipients.\n- Repeat transfer completion rate.\n- Average time to start and complete a repeat transfer.\n- Error rate from incorrect recipient details.\n- Support tickets about recipient entry.\n\nYou also need guardrail metrics. A guardrail metric catches harm while the main metric improves. For saved recipients, guardrails might include failed transfers, fraud alerts, mistaken recipient reports, or account takeover signals.\n\nThe feature is not successful if completion goes up because the app made it too easy to send money to the wrong person.",
  "commonMistakes": "A common mistake is calling an output a success metric. \"Feature launched\" is a delivery milestone, not proof of user value.\n\nAnother mistake is using vanity metrics. A click can be curiosity, confusion, or success. You need context.\n\nA third mistake is choosing too many metrics. If everything is important, the team may not know what to optimize."
};
