import type { Question } from "../questionTypes";

export const lesson: Question = {
  "id": "tpm-technical-product-strategy",
  "track": "TPM",
  "category": "Technical Strategy",
  "level": "Intermediate",
  "question": "How would you create a technical product strategy?",
  "lessonSections": [
    {
      "title": "Learn it",
      "body": "A technical product strategy explains where the product should go, why that direction matters, and what technical bets are needed to get there.\n\nThe beginner mistake is thinking strategy means \"a list of features.\" A feature list says what the team might build. A strategy explains the logic behind the choices. It says which customer problem matters most, which market or business goal the product supports, what the product must become technically, and what the team will deliberately not do.\n\nFor a TPM, the technical part matters because the best product idea may depend on platform readiness, data quality, API reliability, compliance controls, scalability, security, or migration work. If the strategy ignores those realities, the roadmap becomes fantasy.\n\nThe simple mental model is:\n\n```txt\nProduct strategy = where we are going and why.\nTechnical strategy = what capabilities must exist for that direction to be real.\nRoadmap = the sequence of work that moves us there.\n```"
    },
    {
      "title": "Walkthrough",
      "body": "Imagine a remittance company wants to serve small businesses, not only individual senders.\n\nA shallow strategy says:\n\n```txt\nBuild business accounts.\nAdd bulk payments.\nAdd team permissions.\nAdd invoices.\n```\n\nThat is not enough. It does not explain why these things matter, which customer segment comes first, or what platform work is required.\n\nA stronger strategy says:\n\n```txt\nGoal:\nHelp small import/export businesses pay suppliers faster and with clearer tracking.\n\nTarget customer:\nBusinesses sending recurring payments to a known set of suppliers.\n\nWinning promise:\nReliable cross-border payouts, predictable fees, payment status visibility, and audit-friendly records.\n\nTechnical bets:\n- Business identity verification, not only individual KYC.\n- Recipient directory with reusable supplier profiles.\n- Bulk payout workflow with idempotent creation.\n- Role-based access for owner, finance user, and viewer.\n- Reconciliation reports for accounting.\n- Monitoring for payout delays and failed corridors.\n\nNon-goals for now:\n- Full invoicing product.\n- Payroll.\n- Card issuing.\n```\n\nNow the team can make better tradeoffs. If engineering says bulk payouts require a new payout orchestration layer, that is not \"backend work nobody sees.\" It is a strategic capability."
    },
    {
      "title": "Make it practical",
      "body": "I would create the strategy in layers.\n\nFirst, define the product goal. What outcome should change for customers or the business?\n\nSecond, define the customer and use case. Strategy gets weak when it tries to serve everyone.\n\nThird, define the product promise. What should the customer trust us to do better than alternatives?\n\nFourth, map the technical capabilities needed to keep that promise.\n\nFifth, turn those capabilities into sequencing. Some capabilities unlock others. For example, team permissions may need an organization model first.\n\nHere is a practical artifact:\n\n```txt\nTechnical product strategy brief\n\nCustomer problem:\nSmall businesses need repeatable supplier payments with reliable status and records.\n\nBusiness goal:\nGrow business transaction volume while keeping compliance and operations cost under control.\n\nProduct bet:\nBusiness customers value reliability, repeatability, and auditability more than a long menu of features.\n\nRequired capabilities:\n1. Business verification\n2. Organization and roles model\n3. Recipient directory\n4. Bulk payout creation\n5. Reconciliation export\n6. Corridor health monitoring\n\nMain risks:\n- Compliance review takes longer than planned.\n- Bulk retries create duplicate payouts.\n- Support cannot investigate business account issues.\n\nFirst milestone:\nBusiness profile + saved recipients + single payout with business audit trail.\n```\n\nThis artifact is useful because it connects user value, business value, and technical work in one place."
    },
    {
      "title": "Common mistakes",
      "body": "A common mistake is writing strategy as a slogan. \"Be the best API platform\" is not strategy unless it says which users, which advantage, and which capabilities matter.\n\nAnother mistake is hiding technical foundation work. If the roadmap only shows visible features, leadership may not understand why platform work is required.\n\nA third mistake is ignoring tradeoffs. A strategy should make choices. If every customer segment and every feature is equally important, the team has no strategy."
    }
  ],
  "answer": "A technical product strategy explains where the product should go, why that direction matters, and what technical bets are needed to get there.",
  "reasoning": "I would create the strategy in layers.\n\nFirst, define the product goal. What outcome should change for customers or the business?\n\nSecond, define the customer and use case. Strategy gets weak when it tries to serve everyone.\n\nThird, define the product promise. What should the customer trust us to do better than alternatives?\n\nFourth, map the technical capabilities needed to keep that promise.\n\nFifth, turn those capabilities into sequencing. Some capabilities unlock others. For example, team permissions may need an organization model first.\n\nHere is a practical artifact:\n\n```txt\nTechnical product strategy brief\n\nCustomer problem:\nSmall businesses need repeatable supplier payments with reliable status and records.\n\nBusiness goal:\nGrow business transaction volume while keeping compliance and operations cost under control.\n\nProduct bet:\nBusiness customers value reliability, repeatability, and auditability more than a long menu of features.\n\nRequired capabilities:\n1. Business verification\n2. Organization and roles model\n3. Recipient directory\n4. Bulk payout creation\n5. Reconciliation export\n6. Corridor health monitoring\n\nMain risks:\n- Compliance review takes longer than planned.\n- Bulk retries create duplicate payouts.\n- Support cannot investigate business account issues.\n\nFirst milestone:\nBusiness profile + saved recipients + single payout with business audit trail.\n```\n\nThis artifact is useful because it connects user value, business value, and technical work in one place.",
  "tests": "Use the prompts to check whether the idea is clear enough to explain without memorizing.",
  "followUps": [
    "What is the difference between strategy and roadmap?",
    "Why does a TPM need to connect product goals to technical capabilities?",
    "What makes a technical capability strategic instead of just implementation detail?",
    "Why should a strategy include non-goals?",
    "What would make a strategy too vague to guide decisions?"
  ],
  "interviewAnswer": "I would create a technical product strategy by defining the customer, the product promise, the business goal, the technical capabilities needed to deliver that promise, the sequencing of those capabilities, the risks, and the explicit non-goals.\n\nA strong TPM answer shows that strategy is not a feature list. It is the reasoning that helps the team choose what to build, what to defer, and which technical investments are necessary for the product direction to work.",
  "sourceLinks": [
    {
      "label": "ProductPlan: Product strategy",
      "url": "https://www.productplan.com/learn/product-strategy/"
    },
    {
      "label": "Atlassian: Agile roadmaps",
      "url": "https://www.atlassian.com/agile/product-management/roadmaps"
    }
  ],
  "beginnerExplanation": "A technical product strategy explains where the product should go, why that direction matters, and what technical bets are needed to get there.\n\nThe beginner mistake is thinking strategy means \"a list of features.\" A feature list says what the team might build. A strategy explains the logic behind the choices. It says which customer problem matters most, which market or business goal the product supports, what the product must become technically, and what the team will deliberately not do.\n\nFor a TPM, the technical part matters because the best product idea may depend on platform readiness, data quality, API reliability, compliance controls, scalability, security, or migration work. If the strategy ignores those realities, the roadmap becomes fantasy.\n\nThe simple mental model is:\n\n```txt\nProduct strategy = where we are going and why.\nTechnical strategy = what capabilities must exist for that direction to be real.\nRoadmap = the sequence of work that moves us there.\n```",
  "example": "Imagine a remittance company wants to serve small businesses, not only individual senders.\n\nA shallow strategy says:\n\n```txt\nBuild business accounts.\nAdd bulk payments.\nAdd team permissions.\nAdd invoices.\n```\n\nThat is not enough. It does not explain why these things matter, which customer segment comes first, or what platform work is required.\n\nA stronger strategy says:\n\n```txt\nGoal:\nHelp small import/export businesses pay suppliers faster and with clearer tracking.\n\nTarget customer:\nBusinesses sending recurring payments to a known set of suppliers.\n\nWinning promise:\nReliable cross-border payouts, predictable fees, payment status visibility, and audit-friendly records.\n\nTechnical bets:\n- Business identity verification, not only individual KYC.\n- Recipient directory with reusable supplier profiles.\n- Bulk payout workflow with idempotent creation.\n- Role-based access for owner, finance user, and viewer.\n- Reconciliation reports for accounting.\n- Monitoring for payout delays and failed corridors.\n\nNon-goals for now:\n- Full invoicing product.\n- Payroll.\n- Card issuing.\n```\n\nNow the team can make better tradeoffs. If engineering says bulk payouts require a new payout orchestration layer, that is not \"backend work nobody sees.\" It is a strategic capability.",
  "commonMistakes": "A common mistake is writing strategy as a slogan. \"Be the best API platform\" is not strategy unless it says which users, which advantage, and which capabilities matter.\n\nAnother mistake is hiding technical foundation work. If the roadmap only shows visible features, leadership may not understand why platform work is required.\n\nA third mistake is ignoring tradeoffs. A strategy should make choices. If every customer segment and every feature is equally important, the team has no strategy."
};
