import type { Question } from "../questionTypes";

export const lesson: Question = {
  "id": "tpm-technical-debt",
  "track": "TPM",
  "category": "Technical Strategy",
  "level": "Intermediate",
  "question": "How would you decide whether to prioritize technical debt?",
  "lessonSections": [
    {
      "title": "Learn it",
      "body": "Technical debt is the future cost created by technical choices that make the system harder to change, operate, understand, or trust. Sometimes debt is taken deliberately to learn quickly. Sometimes it appears accidentally through rushed work, old assumptions, missing tests, weak architecture, or repeated patches.\n\nFor a TPM, the key is to translate technical debt into product and business impact.\n\nEngineering may say, \"This service is hard to maintain.\" That matters, but stakeholders may not know how to compare it against customer-facing work. The TPM can help express the debt as delivery delay, incident risk, support cost, performance issues, onboarding difficulty, compliance risk, or inability to launch future features.\n\nThe question is not \"Should we ever pay down debt?\" Of course. The real question is \"Which debt matters now, and how much should we invest?\""
    },
    {
      "title": "Walkthrough",
      "body": "Imagine the team wants to launch a new payout method, but the payments code has grown messy. Every change creates regressions. Engineers are afraid to touch it. Testing is manual. Status mapping is duplicated across services.\n\nOne option is to build the new payout method on top of the messy system. That might be faster this month but riskier later.\n\nAnother option is to refactor first. That may delay the feature but reduce future delivery risk.\n\nA TPM should make the tradeoff visible:\n\n- How many planned features depend on this area?\n- How often does this area cause incidents or bugs?\n- How much engineering time is lost to rework?\n- What customer or compliance risk exists?\n- Can the debt be reduced incrementally?\n- What is the cost of delaying the user-facing feature?\n\nNow the decision becomes grounded instead of emotional."
    },
    {
      "title": "Make it practical",
      "body": "I would prioritize technical debt when it blocks important product goals, creates repeated incidents, slows delivery significantly, raises compliance or security risk, increases operational load, or makes future changes unsafe.\n\nI would not automatically pause all product work for a vague cleanup project. I would ask engineering to frame the debt in terms of risk and outcomes. For example: \"Refactor payout status handling so new partners can be added in two weeks instead of six, and reduce reconciliation bugs.\"\n\nGood debt work often has a clear scope:\n\n1. What pain are we reducing?\n2. What product work becomes easier afterward?\n3. What risk decreases?\n4. How will we know the investment worked?\n5. Can it be shipped incrementally?\n\nSometimes the right plan is to allocate a percentage of capacity to debt. Sometimes it is to tie debt work to a feature. Sometimes it is to stop and fix a dangerous foundation before continuing.\n\nHere is an example debt sizing artifact:\n\n```txt\nDebt:\nPayout status mapping is duplicated across three services.\n\nProduct impact:\n- New payout partners take six weeks because every partner needs custom status mapping.\n- Support sometimes sees \"unknown\" when the partner has already returned a useful reason.\n- Reconciliation bugs create manual operations work.\n\nEvidence:\n- 7 payout-status bugs in the last quarter\n- 18 support escalations in the last month\n- Two planned partner launches depend on this area\n\nOptions:\n\nOption A: Do nothing now\nBenefit: fastest path to current feature\nCost: partner launches remain slow and risky\n\nOption B: Full rewrite\nBenefit: clean long-term foundation\nCost: delays roadmap by a quarter and carries migration risk\n\nOption C: Incremental debt payment\nBenefit: create one shared status-mapping module while building the next partner\nCost: adds two weeks to the next partner launch\n```\n\nA reasonable TPM recommendation:\n\n```txt\nRecommendation:\nChoose Option C.\n\nWhy:\nThe debt directly affects two planned launches and repeated support issues, but a full rewrite is too large for the current quarter.\n\nSuccess measure:\n- Next partner launch uses shared mapping\n- Status-related support escalations drop by 50 percent\n- New partner status mapping can be configured in days, not weeks\n\nGuardrail:\nDo not expand scope into a full payment-platform rewrite.\n```\n\nThat is the interview move: translate debt into product consequences, compare options, recommend a scoped investment, and define how the team will know it worked."
    },
    {
      "title": "Common mistakes",
      "body": "A common mistake is treating all debt as equal. Some debt is annoying but harmless. Some debt blocks strategy or creates real risk.\n\nAnother mistake is making debt invisible in planning. If the roadmap assumes full feature capacity while the team is constantly paying hidden maintenance costs, the plan is fake.\n\nA third mistake is framing debt as engineering preference instead of business impact. The TPM should help explain why the investment matters in outcomes stakeholders understand."
    }
  ],
  "answer": "Technical debt is the future cost created by technical choices that make the system harder to change, operate, understand, or trust. Sometimes debt is taken deliberately to learn quickly. Sometimes it appears accidentally through rushed work, old assumptions, missing tests, weak architecture, or repeated patches.",
  "reasoning": "I would prioritize technical debt when it blocks important product goals, creates repeated incidents, slows delivery significantly, raises compliance or security risk, increases operational load, or makes future changes unsafe.\n\nI would not automatically pause all product work for a vague cleanup project. I would ask engineering to frame the debt in terms of risk and outcomes. For example: \"Refactor payout status handling so new partners can be added in two weeks instead of six, and reduce reconciliation bugs.\"\n\nGood debt work often has a clear scope:\n\n1. What pain are we reducing?\n2. What product work becomes easier afterward?\n3. What risk decreases?\n4. How will we know the investment worked?\n5. Can it be shipped incrementally?\n\nSometimes the right plan is to allocate a percentage of capacity to debt. Sometimes it is to tie debt work to a feature. Sometimes it is to stop and fix a dangerous foundation before continuing.\n\nHere is an example debt sizing artifact:\n\n```txt\nDebt:\nPayout status mapping is duplicated across three services.\n\nProduct impact:\n- New payout partners take six weeks because every partner needs custom status mapping.\n- Support sometimes sees \"unknown\" when the partner has already returned a useful reason.\n- Reconciliation bugs create manual operations work.\n\nEvidence:\n- 7 payout-status bugs in the last quarter\n- 18 support escalations in the last month\n- Two planned partner launches depend on this area\n\nOptions:\n\nOption A: Do nothing now\nBenefit: fastest path to current feature\nCost: partner launches remain slow and risky\n\nOption B: Full rewrite\nBenefit: clean long-term foundation\nCost: delays roadmap by a quarter and carries migration risk\n\nOption C: Incremental debt payment\nBenefit: create one shared status-mapping module while building the next partner\nCost: adds two weeks to the next partner launch\n```\n\nA reasonable TPM recommendation:\n\n```txt\nRecommendation:\nChoose Option C.\n\nWhy:\nThe debt directly affects two planned launches and repeated support issues, but a full rewrite is too large for the current quarter.\n\nSuccess measure:\n- Next partner launch uses shared mapping\n- Status-related support escalations drop by 50 percent\n- New partner status mapping can be configured in days, not weeks\n\nGuardrail:\nDo not expand scope into a full payment-platform rewrite.\n```\n\nThat is the interview move: translate debt into product consequences, compare options, recommend a scoped investment, and define how the team will know it worked.",
  "tests": "Use the prompts to check whether the idea is clear enough to explain without memorizing.",
  "followUps": [
    "What makes technical debt different from ordinary imperfect code?",
    "How can a TPM translate debt into business impact?",
    "When is it worth prioritizing debt over new features?",
    "Why is vague cleanup hard to justify?",
    "What metrics might show that debt work helped?"
  ],
  "interviewAnswer": "I would prioritize technical debt when it creates meaningful product, reliability, security, compliance, operational, or delivery risk. I would ask engineering to explain the debt in terms of impact: incidents, slower roadmap delivery, manual work, risk exposure, or blocked future features.\n\nThen I would compare options: fix now, fix incrementally alongside feature work, allocate capacity, or defer with explicit risk. A strong answer treats debt as an investment decision, not an engineering preference.",
  "sourceLinks": [
    {
      "label": "Martin Fowler: Technical Debt",
      "url": "https://martinfowler.com/bliki/TechnicalDebt.html"
    },
    {
      "label": "Atlassian: Technical debt",
      "url": "https://www.atlassian.com/agile/software-development/technical-debt"
    }
  ],
  "beginnerExplanation": "Technical debt is the future cost created by technical choices that make the system harder to change, operate, understand, or trust. Sometimes debt is taken deliberately to learn quickly. Sometimes it appears accidentally through rushed work, old assumptions, missing tests, weak architecture, or repeated patches.\n\nFor a TPM, the key is to translate technical debt into product and business impact.\n\nEngineering may say, \"This service is hard to maintain.\" That matters, but stakeholders may not know how to compare it against customer-facing work. The TPM can help express the debt as delivery delay, incident risk, support cost, performance issues, onboarding difficulty, compliance risk, or inability to launch future features.\n\nThe question is not \"Should we ever pay down debt?\" Of course. The real question is \"Which debt matters now, and how much should we invest?\"",
  "example": "Imagine the team wants to launch a new payout method, but the payments code has grown messy. Every change creates regressions. Engineers are afraid to touch it. Testing is manual. Status mapping is duplicated across services.\n\nOne option is to build the new payout method on top of the messy system. That might be faster this month but riskier later.\n\nAnother option is to refactor first. That may delay the feature but reduce future delivery risk.\n\nA TPM should make the tradeoff visible:\n\n- How many planned features depend on this area?\n- How often does this area cause incidents or bugs?\n- How much engineering time is lost to rework?\n- What customer or compliance risk exists?\n- Can the debt be reduced incrementally?\n- What is the cost of delaying the user-facing feature?\n\nNow the decision becomes grounded instead of emotional.",
  "commonMistakes": "A common mistake is treating all debt as equal. Some debt is annoying but harmless. Some debt blocks strategy or creates real risk.\n\nAnother mistake is making debt invisible in planning. If the roadmap assumes full feature capacity while the team is constantly paying hidden maintenance costs, the plan is fake.\n\nA third mistake is framing debt as engineering preference instead of business impact. The TPM should help explain why the investment matters in outcomes stakeholders understand."
};
