import type { Question } from "../questionTypes";

export const lesson: Question = {
  "id": "tpm-release-readiness",
  "track": "TPM",
  "category": "Launch",
  "level": "Intermediate",
  "question": "How would you decide whether a feature is ready to launch?",
  "lessonSections": [
    {
      "title": "Learn it",
      "body": "Launch readiness means the team has enough evidence that the feature can be released without creating unacceptable customer, business, technical, operational, or compliance risk.\n\nIt does not mean the feature is perfect. It means the team understands what is being released, who will see it, what could go wrong, how success will be measured, and how to respond if something breaks.\n\nFor a TPM, launch readiness is a cross-functional decision. Engineering may say the code is complete. Design may say the experience is approved. Compliance may require sign-off. Support may need scripts. Marketing may need timing. Data may need dashboards. Operations may need a runbook.\n\nThe job is to bring those pieces together into a clear go or no-go decision."
    },
    {
      "title": "Walkthrough",
      "body": "Imagine launching a new identity verification flow.\n\nCode complete is not enough. You need to know:\n\n- Does it work on supported devices and browsers?\n- Are the error states understandable?\n- Does the vendor handle expected traffic?\n- Are privacy and compliance requirements approved?\n- Can support see verification status?\n- Are analytics events firing?\n- Do we know the expected approval and failure rates?\n- Can we roll back or disable the flow?\n- What happens to users already in progress if we roll back?\n\nReadiness is about confidence across the whole system, not only the pull request.\n\nHere is what a practical readiness view can look like:\n\n```txt\nArea: Product\nOwner: PM\nEvidence: success metrics, launch scope, non-goals, customer states\nGo/no-go question: Do we know what success and harm look like?\n\nArea: Engineering\nOwner: Engineering lead\nEvidence: tests, monitoring, logs, feature flag, rollback plan\nGo/no-go question: Can we detect and recover if this behaves badly?\n\nArea: Compliance and risk\nOwner: Compliance lead\nEvidence: approval, audit fields, data retention, review workflow\nGo/no-go question: Are required controls present before risky actions?\n\nArea: Support and operations\nOwner: Ops or support lead\nEvidence: runbook, macros, admin visibility, escalation path\nGo/no-go question: Can the company operate the feature on day one?\n```\n\nThis turns \"are we ready?\" from a vague meeting into evidence the team can inspect."
    },
    {
      "title": "Make it practical",
      "body": "I would create a launch checklist with owners.\n\nProduct readiness: requirements complete, non-goals clear, user-facing states approved, success metrics defined, experiment or rollout plan agreed.\n\nEngineering readiness: tests pass, known bugs triaged, monitoring added, logs useful, feature flag ready, rollback plan known, dependencies checked.\n\nDesign readiness: final UX reviewed across key states, copy approved, accessibility considered, mobile and desktop behavior checked.\n\nOperational readiness: support docs, escalation path, admin tools, runbook, manual-review process, and incident contacts.\n\nCompliance and risk readiness: privacy, security, data retention, audit logs, terms, and regulatory approvals if needed.\n\nData readiness: dashboards, event definitions, baseline metrics, alert thresholds, and post-launch review date.\n\nThen I would choose the release shape. A risky feature should not launch to everyone at once if it can be phased. Use internal testing, beta users, percentage rollout, geography-based rollout, feature flags, or limited transaction limits.\n\nA go/no-go decision should be short and explicit:\n\n```txt\nDecision: Go with limited rollout.\n\nScope: 5% of eligible users in one corridor.\nWhy: Happy path, rejection path, and manual review path are tested. Support runbook is ready. Compliance approval is complete.\nKnown risk: Vendor webhook delay could leave users in pending state longer than expected.\nMitigation: Alert if pending exceeds 15 minutes. Support can see vendor status. Rollback disables new submissions without hiding existing cases.\nReview: Meet after 24 hours or after first 500 attempts, whichever comes first.\n```\n\nThat answer sounds senior because it does not pretend launch is risk-free. It shows the risk and the control."
    },
    {
      "title": "Common mistakes",
      "body": "A common mistake is treating readiness as a meeting where everyone gives vague approval. Readiness should be evidence-based.\n\nAnother mistake is forgetting rollback. Some features are easy to turn off. Others involve migrations, customer states, partner calls, or money movement. Rollback must be designed before launch.\n\nA third mistake is not defining success until after launch. If you do not know what healthy looks like, you will not know whether launch is going well."
    }
  ],
  "answer": "Launch readiness means the team has enough evidence that the feature can be released without creating unacceptable customer, business, technical, operational, or compliance risk.",
  "reasoning": "I would create a launch checklist with owners.\n\nProduct readiness: requirements complete, non-goals clear, user-facing states approved, success metrics defined, experiment or rollout plan agreed.\n\nEngineering readiness: tests pass, known bugs triaged, monitoring added, logs useful, feature flag ready, rollback plan known, dependencies checked.\n\nDesign readiness: final UX reviewed across key states, copy approved, accessibility considered, mobile and desktop behavior checked.\n\nOperational readiness: support docs, escalation path, admin tools, runbook, manual-review process, and incident contacts.\n\nCompliance and risk readiness: privacy, security, data retention, audit logs, terms, and regulatory approvals if needed.\n\nData readiness: dashboards, event definitions, baseline metrics, alert thresholds, and post-launch review date.\n\nThen I would choose the release shape. A risky feature should not launch to everyone at once if it can be phased. Use internal testing, beta users, percentage rollout, geography-based rollout, feature flags, or limited transaction limits.\n\nA go/no-go decision should be short and explicit:\n\n```txt\nDecision: Go with limited rollout.\n\nScope: 5% of eligible users in one corridor.\nWhy: Happy path, rejection path, and manual review path are tested. Support runbook is ready. Compliance approval is complete.\nKnown risk: Vendor webhook delay could leave users in pending state longer than expected.\nMitigation: Alert if pending exceeds 15 minutes. Support can see vendor status. Rollback disables new submissions without hiding existing cases.\nReview: Meet after 24 hours or after first 500 attempts, whichever comes first.\n```\n\nThat answer sounds senior because it does not pretend launch is risk-free. It shows the risk and the control.",
  "tests": "Use the prompts to check whether the idea is clear enough to explain without memorizing.",
  "followUps": [
    "Why is code complete not the same as launch ready?",
    "What areas should a launch checklist cover?",
    "Why are feature flags useful for risky releases?",
    "What makes rollback complicated?",
    "What metrics would you watch immediately after launch?"
  ],
  "interviewAnswer": "I would decide launch readiness by checking product, engineering, design, compliance, operations, support, and data readiness. The feature should have clear requirements, tested core paths, acceptable known risks, monitoring, support materials, rollout plan, rollback plan, and success metrics.\n\nFor higher-risk launches, I would use feature flags, limited rollout, beta groups, or geography-based release. A strong answer shows that launch is an operating decision, not just a code-complete milestone.",
  "sourceLinks": [
    {
      "label": "Atlassian: Continuous delivery",
      "url": "https://www.atlassian.com/continuous-delivery"
    },
    {
      "label": "LaunchDarkly: Feature flag best practices",
      "url": "https://launchdarkly.com/blog/feature-flag-best-practices/"
    }
  ],
  "beginnerExplanation": "Launch readiness means the team has enough evidence that the feature can be released without creating unacceptable customer, business, technical, operational, or compliance risk.\n\nIt does not mean the feature is perfect. It means the team understands what is being released, who will see it, what could go wrong, how success will be measured, and how to respond if something breaks.\n\nFor a TPM, launch readiness is a cross-functional decision. Engineering may say the code is complete. Design may say the experience is approved. Compliance may require sign-off. Support may need scripts. Marketing may need timing. Data may need dashboards. Operations may need a runbook.\n\nThe job is to bring those pieces together into a clear go or no-go decision.",
  "example": "Imagine launching a new identity verification flow.\n\nCode complete is not enough. You need to know:\n\n- Does it work on supported devices and browsers?\n- Are the error states understandable?\n- Does the vendor handle expected traffic?\n- Are privacy and compliance requirements approved?\n- Can support see verification status?\n- Are analytics events firing?\n- Do we know the expected approval and failure rates?\n- Can we roll back or disable the flow?\n- What happens to users already in progress if we roll back?\n\nReadiness is about confidence across the whole system, not only the pull request.\n\nHere is what a practical readiness view can look like:\n\n```txt\nArea: Product\nOwner: PM\nEvidence: success metrics, launch scope, non-goals, customer states\nGo/no-go question: Do we know what success and harm look like?\n\nArea: Engineering\nOwner: Engineering lead\nEvidence: tests, monitoring, logs, feature flag, rollback plan\nGo/no-go question: Can we detect and recover if this behaves badly?\n\nArea: Compliance and risk\nOwner: Compliance lead\nEvidence: approval, audit fields, data retention, review workflow\nGo/no-go question: Are required controls present before risky actions?\n\nArea: Support and operations\nOwner: Ops or support lead\nEvidence: runbook, macros, admin visibility, escalation path\nGo/no-go question: Can the company operate the feature on day one?\n```\n\nThis turns \"are we ready?\" from a vague meeting into evidence the team can inspect.",
  "commonMistakes": "A common mistake is treating readiness as a meeting where everyone gives vague approval. Readiness should be evidence-based.\n\nAnother mistake is forgetting rollback. Some features are easy to turn off. Others involve migrations, customer states, partner calls, or money movement. Rollback must be designed before launch.\n\nA third mistake is not defining success until after launch. If you do not know what healthy looks like, you will not know whether launch is going well."
};
