import type { Question } from "../questionTypes";

export const lesson: Question = {
  "id": "tpm-prd",
  "track": "TPM",
  "category": "Product Requirements",
  "level": "Foundational",
  "question": "What makes a strong product requirements document for a technical product?",
  "lessonSections": [
    {
      "title": "Learn it",
      "body": "A product requirements document, or PRD, explains what the team is building, why it matters, who it is for, how success will be measured, and what constraints must be respected.\n\nFor a technical product, a PRD is not just a feature wish list. It is a shared decision document. It helps product, engineering, design, data, support, compliance, operations, and leadership understand the same problem before people start building different things in their heads.\n\nA strong PRD answers four simple questions:\n\n1. What problem are we solving?\n2. Who has this problem?\n3. What should change for the user or business when we solve it?\n4. What must be true for the solution to be safe, usable, and shippable?\n\nIf the PRD cannot answer those questions clearly, engineering may still build something, but the team may not build the right thing."
    },
    {
      "title": "Walkthrough",
      "body": "Imagine the company wants to add scheduled transfers.\n\nA weak PRD says: \"Users should be able to schedule transfers.\"\n\nThat sounds clear until engineering asks questions. Can users schedule one-time or recurring transfers? Can they edit them? What if the exchange rate changes? What if the user's balance is insufficient? What if compliance blocks the recipient before the scheduled date? What notifications are required? What happens on weekends? What does support see?\n\nA strong PRD does not need to solve every technical detail alone, but it should expose the decisions the team must make.\n\nHere is the difference between a vague requirement and a useful requirement:\n\n```txt\nWeak:\nUsers can schedule transfers.\n\nStronger:\nUsers can create a one-time scheduled transfer for a future date up to 90 days away. Before execution, the system must recheck available balance, recipient eligibility, compliance status, and the current exchange rate. If any check fails, the transfer must not execute, the user must receive a clear notification, and support must be able to see the failure reason.\n```\n\nThe stronger version is not longer because the TPM likes paperwork. It is longer because the product has real behavior when money, timing, compliance, and customer trust are involved.\n\nIt might define:\n\n- Target users: customers who send repeat transfers to family.\n- Problem: they forget transfer dates and repeat the same manual steps each month.\n- Goal: increase repeat-transfer completion and reduce manual effort.\n- Non-goals: business transfers and bulk payroll are out of scope.\n- User experience: create, view, pause, edit, cancel, and receive notifications.\n- Technical constraints: rate refresh, balance checks, compliance checks, retry rules, idempotency, audit logs.\n- Metrics: scheduled transfer creation, completion rate, failure rate, support contacts, repeat usage.\n\nNow the team has something real to discuss."
    },
    {
      "title": "Make it practical",
      "body": "For technical products, I like PRDs that include:\n\nProblem and context: why this matters now.\n\nUsers and use cases: who benefits and what they are trying to do.\n\nGoals and non-goals: what is in scope and what is intentionally not in scope.\n\nRequirements: user-facing behavior, system behavior, admin/support behavior, data requirements, permissions, error states, and edge cases.\n\nSuccess metrics: activation, usage, conversion, reliability, latency, cost, quality, or risk metrics.\n\nDependencies and risks: APIs, vendors, migrations, compliance approvals, design dependencies, operational readiness, and rollout risks.\n\nLaunch plan: flags, beta users, monitoring, support docs, rollback, and post-launch review.\n\nThe best PRDs are readable. They do not hide uncertainty. If something is unknown, mark it as an open question with an owner and date. That is better than pretending every decision is already settled.\n\nA useful mini PRD excerpt might look like this:\n\n```txt\nFeature: Scheduled transfers\n\nProblem:\nRepeat senders forget transfer dates and repeat the same manual setup every month.\n\nGoal:\nIncrease repeat-transfer completion and reduce time to send for repeat senders.\n\nNon-goals:\nBulk payroll, business transfers, and multi-recipient schedules are out of scope.\n\nCore flow:\n1. User chooses an existing recipient.\n2. User chooses amount and future date.\n3. User reviews fees, estimated rate, and execution rules.\n4. User confirms schedule.\n5. System checks eligibility again on execution date.\n6. User receives success or failure notification.\n\nEdge cases:\n- Insufficient balance on execution date.\n- Recipient becomes ineligible.\n- Exchange rate changes beyond allowed threshold.\n- Compliance review is required.\n- User cancels before execution.\n\nSuccess metrics:\n- Scheduled transfer creation rate.\n- Scheduled transfer completion rate.\n- Repeat sender retention.\n- Support contacts per scheduled transfer.\n```\n\nThis gives engineering enough shape to ask good technical questions, while still leaving room for implementation design."
    },
    {
      "title": "Common mistakes",
      "body": "A common mistake is writing requirements as solutions too early. \"Use vendor X\" may be correct, but the PRD should also explain the user and business reason so alternatives can be evaluated.\n\nAnother mistake is ignoring non-happy paths. Technical products fail in real ways: timeouts, duplicate requests, permission errors, partial success, partner downtime, migration issues, and manual-review queues.\n\nA third mistake is shipping the PRD as a one-time artifact and never updating it. A PRD should evolve as decisions become clearer."
    }
  ],
  "answer": "A product requirements document, or PRD, explains what the team is building, why it matters, who it is for, how success will be measured, and what constraints must be respected.",
  "reasoning": "For technical products, I like PRDs that include:\n\nProblem and context: why this matters now.\n\nUsers and use cases: who benefits and what they are trying to do.\n\nGoals and non-goals: what is in scope and what is intentionally not in scope.\n\nRequirements: user-facing behavior, system behavior, admin/support behavior, data requirements, permissions, error states, and edge cases.\n\nSuccess metrics: activation, usage, conversion, reliability, latency, cost, quality, or risk metrics.\n\nDependencies and risks: APIs, vendors, migrations, compliance approvals, design dependencies, operational readiness, and rollout risks.\n\nLaunch plan: flags, beta users, monitoring, support docs, rollback, and post-launch review.\n\nThe best PRDs are readable. They do not hide uncertainty. If something is unknown, mark it as an open question with an owner and date. That is better than pretending every decision is already settled.\n\nA useful mini PRD excerpt might look like this:\n\n```txt\nFeature: Scheduled transfers\n\nProblem:\nRepeat senders forget transfer dates and repeat the same manual setup every month.\n\nGoal:\nIncrease repeat-transfer completion and reduce time to send for repeat senders.\n\nNon-goals:\nBulk payroll, business transfers, and multi-recipient schedules are out of scope.\n\nCore flow:\n1. User chooses an existing recipient.\n2. User chooses amount and future date.\n3. User reviews fees, estimated rate, and execution rules.\n4. User confirms schedule.\n5. System checks eligibility again on execution date.\n6. User receives success or failure notification.\n\nEdge cases:\n- Insufficient balance on execution date.\n- Recipient becomes ineligible.\n- Exchange rate changes beyond allowed threshold.\n- Compliance review is required.\n- User cancels before execution.\n\nSuccess metrics:\n- Scheduled transfer creation rate.\n- Scheduled transfer completion rate.\n- Repeat sender retention.\n- Support contacts per scheduled transfer.\n```\n\nThis gives engineering enough shape to ask good technical questions, while still leaving room for implementation design.",
  "tests": "Use the prompts to check whether the idea is clear enough to explain without memorizing.",
  "followUps": [
    "What problem should a PRD solve for the team?",
    "Why are non-goals useful?",
    "What kinds of edge cases matter in a technical PRD?",
    "Why should success metrics be included before build starts?",
    "How should a PRD handle unknowns?"
  ],
  "interviewAnswer": "A strong technical PRD aligns the team on the problem, user, scope, requirements, constraints, metrics, risks, and launch plan. It should include goals, non-goals, user flows, system behavior, edge cases, data needs, dependencies, open questions, and success measures.\n\nThe best PRDs are not long for the sake of being long. They make decisions clear, expose uncertainty, and prevent teams from building different interpretations of the same feature.",
  "sourceLinks": [
    {
      "label": "ProductPlan: Product requirements document",
      "url": "https://www.productplan.com/glossary/product-requirements-document/"
    },
    {
      "label": "Atlassian: Product requirements template",
      "url": "https://www.atlassian.com/software/confluence/templates/product-requirements"
    }
  ],
  "beginnerExplanation": "A product requirements document, or PRD, explains what the team is building, why it matters, who it is for, how success will be measured, and what constraints must be respected.\n\nFor a technical product, a PRD is not just a feature wish list. It is a shared decision document. It helps product, engineering, design, data, support, compliance, operations, and leadership understand the same problem before people start building different things in their heads.\n\nA strong PRD answers four simple questions:\n\n1. What problem are we solving?\n2. Who has this problem?\n3. What should change for the user or business when we solve it?\n4. What must be true for the solution to be safe, usable, and shippable?\n\nIf the PRD cannot answer those questions clearly, engineering may still build something, but the team may not build the right thing.",
  "example": "Imagine the company wants to add scheduled transfers.\n\nA weak PRD says: \"Users should be able to schedule transfers.\"\n\nThat sounds clear until engineering asks questions. Can users schedule one-time or recurring transfers? Can they edit them? What if the exchange rate changes? What if the user's balance is insufficient? What if compliance blocks the recipient before the scheduled date? What notifications are required? What happens on weekends? What does support see?\n\nA strong PRD does not need to solve every technical detail alone, but it should expose the decisions the team must make.\n\nHere is the difference between a vague requirement and a useful requirement:\n\n```txt\nWeak:\nUsers can schedule transfers.\n\nStronger:\nUsers can create a one-time scheduled transfer for a future date up to 90 days away. Before execution, the system must recheck available balance, recipient eligibility, compliance status, and the current exchange rate. If any check fails, the transfer must not execute, the user must receive a clear notification, and support must be able to see the failure reason.\n```\n\nThe stronger version is not longer because the TPM likes paperwork. It is longer because the product has real behavior when money, timing, compliance, and customer trust are involved.\n\nIt might define:\n\n- Target users: customers who send repeat transfers to family.\n- Problem: they forget transfer dates and repeat the same manual steps each month.\n- Goal: increase repeat-transfer completion and reduce manual effort.\n- Non-goals: business transfers and bulk payroll are out of scope.\n- User experience: create, view, pause, edit, cancel, and receive notifications.\n- Technical constraints: rate refresh, balance checks, compliance checks, retry rules, idempotency, audit logs.\n- Metrics: scheduled transfer creation, completion rate, failure rate, support contacts, repeat usage.\n\nNow the team has something real to discuss.",
  "commonMistakes": "A common mistake is writing requirements as solutions too early. \"Use vendor X\" may be correct, but the PRD should also explain the user and business reason so alternatives can be evaluated.\n\nAnother mistake is ignoring non-happy paths. Technical products fail in real ways: timeouts, duplicate requests, permission errors, partial success, partner downtime, migration issues, and manual-review queues.\n\nA third mistake is shipping the PRD as a one-time artifact and never updating it. A PRD should evolve as decisions become clearer."
};
