import type { Question } from "./questionTypes";

export const questionSummaries: Question[] = [
  {
    "id": "fe-closures",
    "track": "Frontend",
    "category": "JavaScript",
    "level": "Foundational",
    "question": "Explain closures in JavaScript.",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-controlled-components",
    "track": "Frontend",
    "category": "React",
    "level": "Foundational",
    "question": "What is the difference between controlled and uncontrolled components in React?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-core-web-vitals",
    "track": "Frontend",
    "category": "Performance",
    "level": "Intermediate",
    "question": "What are Core Web Vitals, and how would you improve them?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-css-cascade-specificity-stacking",
    "track": "Frontend",
    "category": "CSS",
    "level": "Intermediate",
    "question": "Explain the CSS cascade, specificity, and stacking context.",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-data-fetching-cache-invalidation",
    "track": "Frontend",
    "category": "React",
    "level": "Intermediate",
    "question": "How should frontend apps handle data fetching and cache invalidation?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-debounce-throttle",
    "track": "Frontend",
    "category": "JavaScript",
    "level": "Foundational",
    "question": "What is the difference between debounce and throttle?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-event-loop",
    "track": "Frontend",
    "category": "JavaScript",
    "level": "Intermediate",
    "question": "Explain the JavaScript event loop.",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-event-propagation-delegation",
    "track": "Frontend",
    "category": "JavaScript",
    "level": "Foundational",
    "question": "Explain event propagation and event delegation in the browser.",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-flexbox-grid",
    "track": "Frontend",
    "category": "CSS",
    "level": "Foundational",
    "question": "When would you use Flexbox versus CSS Grid?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-promises-async-await",
    "track": "Frontend",
    "category": "JavaScript",
    "level": "Foundational",
    "question": "Explain Promises and async/await in JavaScript.",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-props-state",
    "track": "Frontend",
    "category": "React",
    "level": "Foundational",
    "question": "What is the difference between props and state in React?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-react-keys",
    "track": "Frontend",
    "category": "React",
    "level": "Intermediate",
    "question": "Why are keys important when rendering lists in React?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-react-rerenders",
    "track": "Frontend",
    "category": "React",
    "level": "Intermediate",
    "question": "What causes React components to re-render?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-semantic-html",
    "track": "Frontend",
    "category": "Accessibility",
    "level": "Foundational",
    "question": "Why does semantic HTML matter?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-testing-confidence",
    "track": "Frontend",
    "category": "Testing",
    "level": "Intermediate",
    "question": "What should you test in a frontend app?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-use-effect",
    "track": "Frontend",
    "category": "React",
    "level": "Intermediate",
    "question": "What should go in useEffect?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-xss",
    "track": "Frontend",
    "category": "Security",
    "level": "Intermediate",
    "question": "What is cross-site scripting, and how do you prevent it?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ambiguous-executive-ask",
    "track": "TPM",
    "category": "Product Strategy",
    "level": "Intermediate",
    "question": "How would you handle an ambiguous executive request?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-api-integration",
    "track": "TPM",
    "category": "API & Partner Integration",
    "level": "Foundational",
    "question": "How would you manage the launch of a new third-party API integration?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-api-product-design",
    "track": "TPM",
    "category": "API & Partner Integration",
    "level": "Intermediate",
    "question": "How would you design an API product from scratch?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-api-versioning",
    "track": "TPM",
    "category": "API & Partner Integration",
    "level": "Intermediate",
    "question": "How would you handle API versioning and backwards compatibility?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-build-versus-buy",
    "track": "TPM",
    "category": "Technical Strategy",
    "level": "Intermediate",
    "question": "How would you make a build versus buy decision?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-compliance-ux",
    "track": "TPM",
    "category": "Compliance & Risk",
    "level": "Intermediate",
    "question": "How would you design a compliant onboarding flow without hurting conversion too much?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-data-product-reporting-requirements",
    "track": "TPM",
    "category": "Data & Reporting",
    "level": "Intermediate",
    "question": "How would you define requirements for a reporting or data product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-dependency-risk",
    "track": "TPM",
    "category": "Execution & Delivery",
    "level": "Intermediate",
    "question": "How would you manage dependency risk across multiple teams?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-enterprise-permissions-auditability",
    "track": "TPM",
    "category": "Enterprise Product",
    "level": "Intermediate",
    "question": "How would you design enterprise permissions, roles, and auditability?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-experiment-design-risk",
    "track": "TPM",
    "category": "Metrics & Experimentation",
    "level": "Intermediate",
    "question": "How would you design an experiment when the product area has compliance or user-risk constraints?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-fraud-compliance-tradeoffs",
    "track": "TPM",
    "category": "Risk & Compliance",
    "level": "Intermediate",
    "question": "How would you balance fraud prevention, compliance, and user experience?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-incident-management",
    "track": "TPM",
    "category": "Operations",
    "level": "Intermediate",
    "question": "How would you handle a production incident affecting customers?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-internal-tools",
    "track": "TPM",
    "category": "Internal Tools",
    "level": "Foundational",
    "question": "How would you prioritize and build an internal tool for operations or support teams?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-migration-communications",
    "track": "TPM",
    "category": "Migration & Change Management",
    "level": "Intermediate",
    "question": "How would you communicate a technical migration to customers and internal teams?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-migration-planning",
    "track": "TPM",
    "category": "Technical Strategy",
    "level": "Intermediate",
    "question": "How would you plan a platform or data migration?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-onboarding-activation-metrics",
    "track": "TPM",
    "category": "Metrics",
    "level": "Foundational",
    "question": "How would you measure onboarding and activation for a product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-partner-outage-fallback",
    "track": "TPM",
    "category": "Operations",
    "level": "Intermediate",
    "question": "How would you handle a critical partner API outage?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-payments-remittance-requirements",
    "track": "TPM",
    "category": "Product Requirements",
    "level": "Intermediate",
    "question": "How would you define requirements for a payments or remittance feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-platform-product-sense",
    "track": "TPM",
    "category": "Platform Product",
    "level": "Intermediate",
    "question": "How would you show product sense for a platform or developer product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-post-launch-operations",
    "track": "TPM",
    "category": "Operations",
    "level": "Intermediate",
    "question": "What would you monitor after launching a high-risk product feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-prd",
    "track": "TPM",
    "category": "Product Requirements",
    "level": "Foundational",
    "question": "What makes a strong product requirements document for a technical product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-prioritization",
    "track": "TPM",
    "category": "Product Strategy",
    "level": "Intermediate",
    "question": "How do you prioritize a roadmap when engineering capacity is limited?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-privacy-by-design",
    "track": "TPM",
    "category": "Security & Compliance",
    "level": "Intermediate",
    "question": "How would you apply privacy by design to a new product feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-release-readiness",
    "track": "TPM",
    "category": "Launch",
    "level": "Intermediate",
    "question": "How would you decide whether a feature is ready to launch?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-roadmap-cross-functional-pressure",
    "track": "TPM",
    "category": "Roadmap & Prioritization",
    "level": "Intermediate",
    "question": "How would you build a roadmap when engineering, compliance, sales, and leadership all want different things?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-security-review-product-manager",
    "track": "TPM",
    "category": "Security & Compliance",
    "level": "Intermediate",
    "question": "How should a product manager work with security review?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-stakeholder-alignment",
    "track": "TPM",
    "category": "Stakeholder Management",
    "level": "Intermediate",
    "question": "How would you handle conflicting stakeholder priorities?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-success-metrics",
    "track": "TPM",
    "category": "Metrics",
    "level": "Foundational",
    "question": "How would you choose success metrics for a product feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-support-feedback-loop",
    "track": "TPM",
    "category": "Discovery & Feedback",
    "level": "Foundational",
    "question": "How would you turn support tickets and customer feedback into product decisions?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-technical-debt",
    "track": "TPM",
    "category": "Technical Strategy",
    "level": "Intermediate",
    "question": "How would you decide whether to prioritize technical debt?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-technical-product-strategy",
    "track": "TPM",
    "category": "Technical Strategy",
    "level": "Intermediate",
    "question": "How would you create a technical product strategy?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-technical-tradeoffs",
    "track": "TPM",
    "category": "Technical Strategy",
    "level": "Intermediate",
    "question": "How would you explain a technical tradeoff to non-technical stakeholders?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-usage-based-pricing-packaging",
    "track": "TPM",
    "category": "Pricing & Packaging",
    "level": "Intermediate",
    "question": "How would you design pricing and packaging for an API or usage-based product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-user-stories",
    "track": "TPM",
    "category": "Product Requirements",
    "level": "Foundational",
    "question": "How do you write good user stories and acceptance criteria?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-vendor-evaluation",
    "track": "TPM",
    "category": "API & Partner Integration",
    "level": "Intermediate",
    "question": "How would you evaluate a third-party vendor for a technical product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  }
];
