import type { Question } from "./questionTypes";

export const questionSummaries: Question[] = [
  {
    "id": "fe-closures",
    "track": "Frontend",
    "category": "JavaScript",
    "level": "Foundational",
    "question": "Explain closures in JavaScript.",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-controlled-components",
    "track": "Frontend",
    "category": "React",
    "level": "Foundational",
    "question": "What is the difference between controlled and uncontrolled components in React?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-core-web-vitals",
    "track": "Frontend",
    "category": "Performance",
    "level": "Intermediate",
    "question": "What are Core Web Vitals, and how would you improve them?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-css-cascade-specificity-stacking",
    "track": "Frontend",
    "category": "CSS",
    "level": "Intermediate",
    "question": "Explain the CSS cascade, specificity, and stacking context.",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-data-fetching-cache-invalidation",
    "track": "Frontend",
    "category": "React",
    "level": "Intermediate",
    "question": "How should frontend apps handle data fetching and cache invalidation?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-debounce-throttle",
    "track": "Frontend",
    "category": "JavaScript",
    "level": "Foundational",
    "question": "What is the difference between debounce and throttle?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-event-loop",
    "track": "Frontend",
    "category": "JavaScript",
    "level": "Intermediate",
    "question": "Explain the JavaScript event loop.",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-event-propagation-delegation",
    "track": "Frontend",
    "category": "JavaScript",
    "level": "Foundational",
    "question": "Explain event propagation and event delegation in the browser.",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-flexbox-grid",
    "track": "Frontend",
    "category": "CSS",
    "level": "Foundational",
    "question": "When would you use Flexbox versus CSS Grid?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-promises-async-await",
    "track": "Frontend",
    "category": "JavaScript",
    "level": "Foundational",
    "question": "Explain Promises and async/await in JavaScript.",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-props-state",
    "track": "Frontend",
    "category": "React",
    "level": "Foundational",
    "question": "What is the difference between props and state in React?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-react-keys",
    "track": "Frontend",
    "category": "React",
    "level": "Intermediate",
    "question": "Why are keys important when rendering lists in React?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-react-rerenders",
    "track": "Frontend",
    "category": "React",
    "level": "Intermediate",
    "question": "What causes React components to re-render?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-semantic-html",
    "track": "Frontend",
    "category": "Accessibility",
    "level": "Foundational",
    "question": "Why does semantic HTML matter?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-testing-confidence",
    "track": "Frontend",
    "category": "Testing",
    "level": "Intermediate",
    "question": "What should you test in a frontend app?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-use-effect",
    "track": "Frontend",
    "category": "React",
    "level": "Intermediate",
    "question": "What should go in useEffect?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "fe-xss",
    "track": "Frontend",
    "category": "Security",
    "level": "Intermediate",
    "question": "What is cross-site scripting, and how do you prevent it?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-account-freeze-appeals",
    "track": "TPM",
    "category": "Fraud & Risk",
    "level": "Intermediate",
    "question": "How would you design an account freeze and appeal experience?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ach-return-risk-monitoring",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Intermediate",
    "question": "How would you monitor ACH return risk?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-agent-payment-action-approval",
    "track": "TPM",
    "category": "AI Product",
    "level": "Advanced",
    "question": "How would you design approval controls for an AI agent that can take payment actions?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-agent-tool-permissions",
    "track": "TPM",
    "category": "AI Agents",
    "level": "Intermediate",
    "question": "How would you design permissions for an AI agent that can use tools?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-aml-alert-triage-copilot",
    "track": "TPM",
    "category": "AI & Risk",
    "level": "Advanced",
    "question": "How would you design an AI copilot for AML alert triage?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-audit-logs-regulated-workflows",
    "track": "TPM",
    "category": "AI Governance",
    "level": "Advanced",
    "question": "What should AI audit logs capture in regulated fintech workflows?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-credit-underwriting",
    "track": "TPM",
    "category": "AI & Fintech",
    "level": "Intermediate",
    "question": "How would you approach AI-assisted credit underwriting as a TPM?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-customer-communications-review",
    "track": "TPM",
    "category": "AI Product",
    "level": "Advanced",
    "question": "How would you use AI to draft customer communications in a regulated fintech product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-data-privacy-retention",
    "track": "TPM",
    "category": "AI Governance",
    "level": "Intermediate",
    "question": "How would you handle data privacy and retention for an AI feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-document-verification-workflow",
    "track": "TPM",
    "category": "AI Product",
    "level": "Intermediate",
    "question": "How would you design AI-assisted document verification?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-eval-dataset-governance",
    "track": "TPM",
    "category": "AI Governance",
    "level": "Advanced",
    "question": "How would you govern evaluation datasets for an AI feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-explainability-risk-decisions",
    "track": "TPM",
    "category": "AI & Risk",
    "level": "Advanced",
    "question": "How would you make AI-assisted risk decisions explainable?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-fraud-detection",
    "track": "TPM",
    "category": "AI & Risk",
    "level": "Intermediate",
    "question": "How would you design an AI-assisted fraud detection product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-governance-risk-tiering",
    "track": "TPM",
    "category": "AI Governance",
    "level": "Intermediate",
    "question": "How would you create a risk-tiering model for AI features?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-incident-response-model-failure",
    "track": "TPM",
    "category": "AI Governance",
    "level": "Advanced",
    "question": "How would you handle an incident caused by an AI model failure?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-knowledge-base-grounding",
    "track": "TPM",
    "category": "AI Product",
    "level": "Intermediate",
    "question": "How would you keep an AI assistant grounded in an approved knowledge base?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-model-evaluation",
    "track": "TPM",
    "category": "AI Product",
    "level": "Intermediate",
    "question": "How would you evaluate whether an AI feature is ready to launch?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-observability-monitoring",
    "track": "TPM",
    "category": "AI Operations",
    "level": "Intermediate",
    "question": "What would you monitor for an AI feature in production?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-red-team-fintech-assistant",
    "track": "TPM",
    "category": "AI Governance",
    "level": "Advanced",
    "question": "How would you red-team an AI assistant for a fintech product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-support-agent-regulated-fintech",
    "track": "TPM",
    "category": "AI & Customer Operations",
    "level": "Intermediate",
    "question": "How would you launch an AI support agent in a regulated fintech product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ai-vendor-evaluation",
    "track": "TPM",
    "category": "AI Product",
    "level": "Intermediate",
    "question": "How would you evaluate an AI vendor for a fintech product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ambiguous-executive-ask",
    "track": "TPM",
    "category": "Product Strategy",
    "level": "Intermediate",
    "question": "How would you handle an ambiguous executive request?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-aml-transaction-monitoring",
    "track": "TPM",
    "category": "Compliance & Risk",
    "level": "Intermediate",
    "question": "How would you define requirements for AML transaction monitoring?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-api-integration",
    "track": "TPM",
    "category": "API & Partner Integration",
    "level": "Foundational",
    "question": "How would you manage the launch of a new third-party API integration?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-api-product-design",
    "track": "TPM",
    "category": "API & Partner Integration",
    "level": "Intermediate",
    "question": "How would you design an API product from scratch?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-api-versioning",
    "track": "TPM",
    "category": "API & Partner Integration",
    "level": "Intermediate",
    "question": "How would you handle API versioning and backwards compatibility?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-audit-trail-product-requirements",
    "track": "TPM",
    "category": "Security & Compliance",
    "level": "Intermediate",
    "question": "What audit trail requirements would you define for a fintech workflow?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-build-versus-buy",
    "track": "TPM",
    "category": "Technical Strategy",
    "level": "Intermediate",
    "question": "How would you make a build versus buy decision?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-card-authorization-decline-controls",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Intermediate",
    "question": "How would you design card authorization and decline controls?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-chargebacks-disputes",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Intermediate",
    "question": "How would you design a product workflow for chargebacks and payment disputes?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-collections-hardship-repayment",
    "track": "TPM",
    "category": "Credit & Lending",
    "level": "Intermediate",
    "question": "How would you design a collections and hardship repayment experience?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-complaints-risk-feedback-loop",
    "track": "TPM",
    "category": "Product Strategy",
    "level": "Intermediate",
    "question": "How would you use customer complaints to improve a fintech product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-compliance-ux",
    "track": "TPM",
    "category": "Compliance & Risk",
    "level": "Intermediate",
    "question": "How would you design a compliant onboarding flow without hurting conversion too much?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-credit-bureau-dispute-workflow",
    "track": "TPM",
    "category": "Credit & Lending",
    "level": "Advanced",
    "question": "How would you design a credit bureau dispute workflow?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-credit-line-change-adverse-action",
    "track": "TPM",
    "category": "Credit & Lending",
    "level": "Advanced",
    "question": "How would you design a credit line increase or decrease workflow?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-data-product-reporting-requirements",
    "track": "TPM",
    "category": "Data & Reporting",
    "level": "Intermediate",
    "question": "How would you define requirements for a reporting or data product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-data-retention-deletion-fintech",
    "track": "TPM",
    "category": "Security & Compliance",
    "level": "Advanced",
    "question": "How would you design data retention and deletion for a fintech product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-dependency-risk",
    "track": "TPM",
    "category": "Execution & Delivery",
    "level": "Intermediate",
    "question": "How would you manage dependency risk across multiple teams?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-dispute-evidence-automation",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Intermediate",
    "question": "How would you automate dispute evidence collection?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-enterprise-permissions-auditability",
    "track": "TPM",
    "category": "Enterprise Product",
    "level": "Intermediate",
    "question": "How would you design enterprise permissions, roles, and auditability?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-experiment-design-risk",
    "track": "TPM",
    "category": "Metrics & Experimentation",
    "level": "Intermediate",
    "question": "How would you design an experiment when the product area has compliance or user-risk constraints?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-fee-transparency-disclosures",
    "track": "TPM",
    "category": "Compliance UX",
    "level": "Intermediate",
    "question": "How would you design fee transparency for a fintech product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-fraud-case-management-tooling",
    "track": "TPM",
    "category": "Fraud & Risk",
    "level": "Intermediate",
    "question": "What should a fraud case management tool include?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-fraud-compliance-tradeoffs",
    "track": "TPM",
    "category": "Risk & Compliance",
    "level": "Intermediate",
    "question": "How would you balance fraud prevention, compliance, and user experience?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-fx-liquidity-remittance",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Intermediate",
    "question": "How would you think about FX, liquidity, and payout reliability in a remittance product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-hallucination-mitigation-fintech",
    "track": "TPM",
    "category": "AI & Customer Operations",
    "level": "Intermediate",
    "question": "How would you reduce hallucination risk in a fintech AI feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-human-in-the-loop-ai-review",
    "track": "TPM",
    "category": "AI Operations",
    "level": "Intermediate",
    "question": "How would you design a human-in-the-loop review workflow for AI decisions?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-incident-management",
    "track": "TPM",
    "category": "Operations",
    "level": "Intermediate",
    "question": "How would you handle a production incident affecting customers?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-internal-tools",
    "track": "TPM",
    "category": "Internal Tools",
    "level": "Foundational",
    "question": "How would you prioritize and build an internal tool for operations or support teams?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-kyb-beneficial-ownership-onboarding",
    "track": "TPM",
    "category": "Security & Compliance",
    "level": "Advanced",
    "question": "How would you design KYB onboarding for beneficial ownership?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-ledger-balances-holds",
    "track": "TPM",
    "category": "Fintech Infrastructure",
    "level": "Intermediate",
    "question": "How would you define product requirements for a ledger, balances, and holds system?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-llm-cost-latency-tradeoffs",
    "track": "TPM",
    "category": "AI Product",
    "level": "Intermediate",
    "question": "How would you manage cost and latency tradeoffs for an LLM-powered feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-merchant-underwriting-onboarding",
    "track": "TPM",
    "category": "Fraud & Risk",
    "level": "Advanced",
    "question": "How would you design merchant onboarding and underwriting for payments?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-migration-communications",
    "track": "TPM",
    "category": "Migration & Change Management",
    "level": "Intermediate",
    "question": "How would you communicate a technical migration to customers and internal teams?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-migration-planning",
    "track": "TPM",
    "category": "Technical Strategy",
    "level": "Intermediate",
    "question": "How would you plan a platform or data migration?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-model-drift-risk-systems",
    "track": "TPM",
    "category": "AI & Risk",
    "level": "Intermediate",
    "question": "How would you monitor model drift in an AI risk system?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-negative-balance-recovery",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Intermediate",
    "question": "How would you design negative balance recovery?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-onboarding-activation-metrics",
    "track": "TPM",
    "category": "Metrics",
    "level": "Foundational",
    "question": "How would you measure onboarding and activation for a product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-open-banking-consent-data-access",
    "track": "TPM",
    "category": "Data & Schema Design",
    "level": "Advanced",
    "question": "How would you design an open banking consent and data access flow?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-partner-bank-incident-comms",
    "track": "TPM",
    "category": "Observability & Operations",
    "level": "Advanced",
    "question": "How would you handle customer communications during a partner bank incident?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-partner-outage-fallback",
    "track": "TPM",
    "category": "Operations",
    "level": "Intermediate",
    "question": "How would you handle a critical partner API outage?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-partner-risk-scorecard",
    "track": "TPM",
    "category": "Vendor & Partner Management",
    "level": "Advanced",
    "question": "How would you build a partner risk scorecard for a fintech vendor?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-payment-webhooks-idempotency",
    "track": "TPM",
    "category": "API & Partner Integration",
    "level": "Intermediate",
    "question": "How would you make payment webhooks reliable and idempotent?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-payments-remittance-requirements",
    "track": "TPM",
    "category": "Product Requirements",
    "level": "Intermediate",
    "question": "How would you define requirements for a payments or remittance feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-payout-reconciliation-reporting",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Intermediate",
    "question": "How would you design payout reconciliation reporting?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-platform-product-sense",
    "track": "TPM",
    "category": "Platform Product",
    "level": "Intermediate",
    "question": "How would you show product sense for a platform or developer product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-post-launch-operations",
    "track": "TPM",
    "category": "Operations",
    "level": "Intermediate",
    "question": "What would you monitor after launching a high-risk product feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-prd",
    "track": "TPM",
    "category": "Product Requirements",
    "level": "Foundational",
    "question": "What makes a strong product requirements document for a technical product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-prioritization",
    "track": "TPM",
    "category": "Product Strategy",
    "level": "Intermediate",
    "question": "How do you prioritize a roadmap when engineering capacity is limited?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-privacy-by-design",
    "track": "TPM",
    "category": "Security & Compliance",
    "level": "Intermediate",
    "question": "How would you apply privacy by design to a new product feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-privacy-request-dsar-fintech",
    "track": "TPM",
    "category": "Security & Compliance",
    "level": "Intermediate",
    "question": "How would you design a privacy data request workflow for fintech users?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-prompt-versioning-change-management",
    "track": "TPM",
    "category": "AI Product",
    "level": "Intermediate",
    "question": "How would you manage prompt changes and versioning in a production AI feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-regulatory-reporting-dashboard",
    "track": "TPM",
    "category": "Security & Compliance",
    "level": "Advanced",
    "question": "How would you design a regulatory reporting dashboard?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-release-readiness",
    "track": "TPM",
    "category": "Launch",
    "level": "Intermediate",
    "question": "How would you decide whether a feature is ready to launch?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-remittance-corridor-expansion",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Advanced",
    "question": "How would you launch a new international remittance corridor?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-risk-queue-prioritization",
    "track": "TPM",
    "category": "Fraud & Risk",
    "level": "Intermediate",
    "question": "How would you design a fraud risk review queue?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-roadmap-cross-functional-pressure",
    "track": "TPM",
    "category": "Roadmap & Prioritization",
    "level": "Intermediate",
    "question": "How would you build a roadmap when engineering, compliance, sales, and leadership all want different things?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-sanctions-screening-false-positives",
    "track": "TPM",
    "category": "Compliance & Risk",
    "level": "Intermediate",
    "question": "How would you design sanctions screening while managing false positives?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-sar-investigation-workflow",
    "track": "TPM",
    "category": "Security & Compliance",
    "level": "Advanced",
    "question": "How would you support a suspicious activity investigation workflow?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-security-review-product-manager",
    "track": "TPM",
    "category": "Security & Compliance",
    "level": "Intermediate",
    "question": "How should a product manager work with security review?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-settlement-cutoff-pending-states",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Intermediate",
    "question": "How would you design pending states around settlement cutoffs?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-settlement-reconciliation-mismatches",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Intermediate",
    "question": "How would you handle settlement and reconciliation mismatches in a fintech product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-stakeholder-alignment",
    "track": "TPM",
    "category": "Stakeholder Management",
    "level": "Intermediate",
    "question": "How would you handle conflicting stakeholder priorities?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-success-metrics",
    "track": "TPM",
    "category": "Metrics",
    "level": "Foundational",
    "question": "How would you choose success metrics for a product feature?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-support-feedback-loop",
    "track": "TPM",
    "category": "Discovery & Feedback",
    "level": "Foundational",
    "question": "How would you turn support tickets and customer feedback into product decisions?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-suspicious-recipient-network-analysis",
    "track": "TPM",
    "category": "Fraud & Risk",
    "level": "Advanced",
    "question": "How would you design product requirements for suspicious recipient network analysis?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-technical-debt",
    "track": "TPM",
    "category": "Technical Strategy",
    "level": "Intermediate",
    "question": "How would you decide whether to prioritize technical debt?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-technical-product-strategy",
    "track": "TPM",
    "category": "Technical Strategy",
    "level": "Intermediate",
    "question": "How would you create a technical product strategy?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-technical-tradeoffs",
    "track": "TPM",
    "category": "Technical Strategy",
    "level": "Intermediate",
    "question": "How would you explain a technical tradeoff to non-technical stakeholders?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-transaction-limits-velocity-controls",
    "track": "TPM",
    "category": "Fraud & Risk",
    "level": "Intermediate",
    "question": "How would you design transaction limits and velocity controls?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-treasury-liquidity-forecasting",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Advanced",
    "question": "How would you design treasury liquidity forecasting for a fintech product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-unauthorized-transfer-reg-e-claims",
    "track": "TPM",
    "category": "Payments & Remittance",
    "level": "Intermediate",
    "question": "How would you handle unauthorized transfer claims in a fintech product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-usage-based-pricing-packaging",
    "track": "TPM",
    "category": "Pricing & Packaging",
    "level": "Intermediate",
    "question": "How would you design pricing and packaging for an API or usage-based product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-user-stories",
    "track": "TPM",
    "category": "Product Requirements",
    "level": "Foundational",
    "question": "How do you write good user stories and acceptance criteria?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  },
  {
    "id": "tpm-vendor-evaluation",
    "track": "TPM",
    "category": "API & Partner Integration",
    "level": "Intermediate",
    "question": "How would you evaluate a third-party vendor for a technical product?",
    "answer": "",
    "reasoning": "",
    "tests": "",
    "followUps": []
  }
];
